version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      wgnet:
        ipv4_address: 172.20.0.3
    depends_on:
      - wireguard-manager
    restart: unless-stopped
    environment:
      - DOMAIN=${DOMAIN}
    command: /bin/sh -c "envsubst '$$DOMAIN' < /etc/nginx/nginx.conf > /tmp/nginx.conf && nginx -g 'daemon off;' -c /tmp/nginx.conf"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    command: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"
    restart: unless-stopped

  wireguard-manager:
    image: wireguard-manager
    container_name: wireguard-manager
    networks:
      wgnet:
        ipv4_address: 172.20.0.2
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./deployments:/app/deployments
    environment:
      - INIT_USERNAME=${INIT_USERNAME:-admin}
      - INIT_PASSWORD=${INIT_PASSWORD}
      - INIT_HOST=${DOMAIN}
      - INSECURE=false
    restart: unless-stopped

networks:
  wgnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24