services:
  wireguard-manager:
    build: .
    container_name: wireguard-manager
    networks:
      wgnet:
        ipv4_address: 172.20.0.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./nginx/sites:/app/nginx/sites
      - ./database:/app/database
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    environment:
      - ROOT_DOMAIN=${ROOT_DOMAIN}
      - INIT_USERNAME=${INIT_USERNAME}
      - INIT_PASSWORD=${INIT_PASSWORD}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    networks:
      wgnet:
        ipv4_address: 172.20.0.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/sites
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    environment:
      - ROOT_DOMAIN=${ROOT_DOMAIN}
    command: /bin/sh -c "envsubst '\$${ROOT_DOMAIN}' < /etc/nginx/nginx.conf > /tmp/nginx.conf && nginx -g 'daemon off;' -c /tmp/nginx.conf"
    restart: unless-stopped
    depends_on:
      - wireguard-manager

networks:
  wgnet:
    external: true
    name: wgnet
