services:
  wireguard-manager:
    build: .
    container_name: wireguard-manager
    networks:
      wgnet:
        ipv4_address: 172.20.0.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./nginx/sites:/app/nginx/sites
      - ./database:/app/database
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    environment:
      - ROOT_DOMAIN=example.com
      - INIT_USERNAME=admin
      - INIT_PASSWORD=your-password
      - CERTBOT_EMAIL=email@example.com
    restart: unless-stopped

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    networks:
      wgnet:
        ipv4_address: 172.20.0.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/sites
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    environment:
      - ROOT_DOMAIN=example.com
    command: /bin/sh -c "envsubst '$$ROOT_DOMAIN' < /etc/nginx/nginx.conf > /tmp/nginx.conf && nginx -g 'daemon off;' -c /tmp/nginx.conf"
    restart: unless-stopped
    depends_on:
      - wireguard-manager

  certbot:
    image: certbot/certbot
    container_name: certbot
    networks:
      wgnet:
        ipv4_address: 172.20.0.4
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot --webroot-path=/var/www/certbot --quiet; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped
    depends_on:
      - nginx-proxy

networks:
  wgnet:
    external: true
    name: wgnet